import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedButtonSelectedWidget2.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedButtonDateUnselectedWidget2.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedButtonUnselectedWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedButtonDateSelectedWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedButtonCreateWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedButtonSecondaryWidget.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedRadiobuttonDateWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedButtonCircleWidget6.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedButtonPrimaryWidget11.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedHeaderWidget14.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/Generated3rdSignInWidget2.dart';
import 'package:flutterapp/money_managerapp/generatedbuttonswidget/generated/GeneratedButtonDisabledWidget.dart';

/* Frame Buttons
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1012.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 445.0,
                      height: 1012.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 236, 236, 236),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 74.0,
                              child: GeneratedButtonPrimaryWidget11(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 258.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 74.0,
                              child: GeneratedButtonSecondaryWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 348.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 74.0,
                              child: GeneratedButtonDisabledWidget(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 8.0,
                              right: 8.0,
                              bottom: null,
                              width: null,
                              height: 128.0,
                              child: GeneratedHeaderWidget14(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 464.0,
                              right: null,
                              bottom: null,
                              width: 64.0,
                              height: 48.0,
                              child: GeneratedButtonDateUnselectedWidget2(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 649.0,
                              right: null,
                              bottom: null,
                              width: 338.0,
                              height: 68.0,
                              child: GeneratedRadiobuttonDateWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 554.0,
                              right: null,
                              bottom: null,
                              width: 64.0,
                              height: 48.0,
                              child: GeneratedButtonDateSelectedWidget1(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 759.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedButtonCircleWidget6(),
                            ),
                            Positioned(
                              left: 109.0,
                              top: 739.0,
                              right: null,
                              bottom: null,
                              width: 190.0,
                              height: 100.0,
                              child: Generated3rdSignInWidget2(),
                            ),
                            Positioned(
                              left: 253.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 39.0,
                              child: GeneratedButtonCreateWidget1(),
                            ),
                            Positioned(
                              left: 260.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedButtonSelectedWidget2(),
                            ),
                            Positioned(
                              left: 262.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedButtonUnselectedWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
