import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedHNoContentWidget10.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedDetailsScrollableWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedAddAccountWidget2.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedContentAddImgWidget3.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedTransactionscrollableWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedListcontent4Widget4.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedAddImgIcon_2Widget4.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedHWidget23.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedCategoriesfullWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedChattnWidget.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedCategoriesscrollableWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedHScrollIconColorWidget.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedIconNoTitleWidget84.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedCategoriesScrollableWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedIconColorWidget10.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedDailylistWidget3.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedAddImgIconWidget.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedAccountfullWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddata1widget/generated/GeneratedVScrollWidget2.dart';

/* Frame Data 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedData1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2075.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 3233.0,
                      height: 2075.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 325.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 439.0,
                              child: GeneratedDailylistWidget3(),
                            ),
                            Positioned(
                              left: 424.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 412.0,
                              child: GeneratedListcontent4Widget4(),
                            ),
                            Positioned(
                              left: 1990.0,
                              top: 114.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 540.0,
                              child: GeneratedCategoriesscrollableWidget1(),
                            ),
                            Positioned(
                              left: 2777.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 90.0,
                              child: GeneratedHWidget23(),
                            ),
                            Positioned(
                              left: 2767.0,
                              top: 223.0,
                              right: null,
                              bottom: null,
                              width: 345.0,
                              height: 80.0,
                              child: GeneratedHNoContentWidget10(),
                            ),
                            Positioned(
                              left: 1466.0,
                              top: 179.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 459.0,
                              child: GeneratedVScrollWidget2(),
                            ),
                            Positioned(
                              left: 2384.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 540.0,
                              child: GeneratedCategoriesfullWidget1(),
                            ),
                            Positioned(
                              left: 2232.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 345.0,
                              height: 360.0,
                              child: GeneratedAccountfullWidget1(),
                            ),
                            Positioned(
                              left: 957.0,
                              top: 98.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 740.0,
                              child: GeneratedTransactionscrollableWidget1(),
                            ),
                            Positioned(
                              left: 2777.0,
                              top: 334.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedIconNoTitleWidget84(),
                            ),
                            Positioned(
                              left: 2883.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedIconColorWidget10(),
                            ),
                            Positioned(
                              left: 2801.0,
                              top: 442.0,
                              right: null,
                              bottom: null,
                              width: 278.0,
                              height: 30.0,
                              child: GeneratedHScrollIconColorWidget(),
                            ),
                            Positioned(
                              left: 1745.0,
                              top: 805.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 741.0,
                              child: GeneratedAddAccountWidget2(),
                            ),
                            Positioned(
                              left: 1182.0,
                              top: 927.0,
                              right: null,
                              bottom: null,
                              width: 323.0,
                              height: 557.0,
                              child: GeneratedCategoriesScrollableWidget1(),
                            ),
                            Positioned(
                              left: 54.0,
                              top: 891.0,
                              right: null,
                              bottom: null,
                              width: 921.0,
                              height: 907.0,
                              child: GeneratedChattnWidget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 63.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 123.0,
                              child: GeneratedContentAddImgWidget3(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 96.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 80.0,
                              child: GeneratedAddImgIcon_2Widget4(),
                            ),
                            Positioned(
                              left: 753.0,
                              top: 96.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 80.0,
                              child: GeneratedAddImgIconWidget(),
                            ),
                            Positioned(
                              left: 2783.0,
                              top: 604.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 527.0,
                              child: GeneratedDetailsScrollableWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
