import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget2/generated/GeneratedCheckboxOptionFilledWidget.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget2/generated/GeneratedCheckboxEmptyWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget2/generated/GeneratedInputMoneyCenterWidget2.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget2/generated/GeneratedCheckboxOptionEmptyWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget2/generated/GeneratedInputMoneyWidget3.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget2/generated/GeneratedCheckboxFilledWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget2/generated/GeneratedHeaderWidget15.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget2/generated/GeneratedIconCheckmarkWidget2.dart';

/* Frame Inputs
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputsWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1012.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 445.0,
                      height: 1012.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 236, 236, 236),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 29.0,
                              child: GeneratedIconCheckmarkWidget2(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 213.0,
                              right: null,
                              bottom: null,
                              width: 98.0,
                              height: 39.0,
                              child: GeneratedCheckboxEmptyWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 323.0,
                              right: null,
                              bottom: null,
                              width: 177.0,
                              height: 40.0,
                              child: GeneratedCheckboxOptionEmptyWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 379.0,
                              right: null,
                              bottom: null,
                              width: 177.0,
                              height: 39.0,
                              child: GeneratedCheckboxOptionFilledWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 39.0,
                              child: GeneratedCheckboxFilledWidget1(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 8.0,
                              right: 8.0,
                              bottom: null,
                              width: null,
                              height: 128.0,
                              child: GeneratedHeaderWidget15(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 506.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 70.0,
                              child: GeneratedInputMoneyCenterWidget2(),
                            ),
                            Positioned(
                              left: 170.0,
                              top: 602.0,
                              right: null,
                              bottom: null,
                              width: 198.0,
                              height: 70.0,
                              child: GeneratedInputMoneyWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
