import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedcolumnchartwidget/generated/GeneratedBigHeader2Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/money_managerapp/generatedcolumnchartwidget/generated/GeneratedColumnchartWidget1.dart';

/* Frame Column chart
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedColumnchartWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth;

                        final double height =
                            constraints.maxHeight * 0.15147783251231528;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: 0,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedBigHeader2Widget(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.31527093596059114;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.042666666666666665,
                      y: constraints.maxHeight * 0.22413793103448276,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedColumnchartWidget1(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
