import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedaccountspopupwidget/generated/GeneratedCategoryhorizontalWidget3.dart';
import 'package:flutterapp/money_managerapp/generatedaccountspopupwidget/generated/GeneratedCategoryhorizontalWidget2.dart';

/* Frame Accounts Popup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAccountsPopupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 198.0,
      height: 90.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 10.0,
              top: 10.0,
              right: null,
              bottom: null,
              width: 178.0,
              height: 30.0,
              child: GeneratedCategoryhorizontalWidget2(),
            ),
            Positioned(
              left: 10.0,
              top: 50.0,
              right: null,
              bottom: null,
              width: 178.0,
              height: 30.0,
              child: GeneratedCategoryhorizontalWidget3(),
            )
          ]),
    ));
  }
}
