import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedratingappwidget/generated/GeneratedBGWidget18.dart';
import 'package:flutterapp/money_managerapp/generatedratingappwidget/generated/GeneratedTextWidget68.dart';
import 'package:flutterapp/money_managerapp/generatedratingappwidget/generated/GeneratedTextimage_downWidget.dart';
import 'package:flutterapp/money_managerapp/generatedratingappwidget/generated/GeneratedButtonPrimaryWidget10.dart';
import 'package:flutterapp/money_managerapp/generatedratingappwidget/generated/GeneratedHUWidget.dart';

/* Frame Rating App
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRatingAppWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 343.0,
      height: 427.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 427.0,
              child: GeneratedBGWidget18(),
            ),
            Positioned(
              left: 45.0,
              top: 84.0,
              right: null,
              bottom: null,
              width: 254.0,
              height: 204.0,
              child: GeneratedTextimage_downWidget(),
            ),
            Positioned(
              left: 16.0,
              top: 307.0,
              right: null,
              bottom: null,
              width: 311.0,
              height: 51.0,
              child: GeneratedButtonPrimaryWidget10(),
            ),
            Positioned(
              left: 16.0,
              top: 376.0,
              right: null,
              bottom: null,
              width: 316.0,
              height: 24.0,
              child: GeneratedHUWidget(),
            ),
            Positioned(
              left: 77.0,
              top: 28.0,
              right: null,
              bottom: null,
              width: 190.0,
              height: 36.0,
              child: GeneratedTextWidget68(),
            )
          ]),
    ));
  }
}
