import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatediconswidget/generated/GeneratedWidget136.dart';
import 'package:flutterapp/money_managerapp/generatediconswidget/generated/GeneratedWidget137.dart';
import 'package:flutterapp/money_managerapp/generatediconswidget/generated/GeneratedWidget138.dart';
import 'package:flutterapp/money_managerapp/generatediconswidget/generated/GeneratedWidget139.dart';
import 'package:flutterapp/money_managerapp/generatediconswidget/generated/GeneratedWidget135.dart';
import 'package:flutterapp/money_managerapp/generatediconswidget/generated/GeneratedWidget141.dart';
import 'package:flutterapp/money_managerapp/generatediconswidget/generated/GeneratedWidget134.dart';
import 'package:flutterapp/money_managerapp/generatediconswidget/generated/GeneratedWidget133.dart';
import 'package:flutterapp/money_managerapp/generatediconswidget/generated/GeneratedWidget132.dart';
import 'package:flutterapp/money_managerapp/generatediconswidget/generated/GeneratedWidget140.dart';

/* Frame Icons
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 502.0,
        height: 202.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 48.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedWidget132(),
              ),
              Positioned(
                left: 96.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedWidget133(),
              ),
              Positioned(
                left: 144.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedWidget134(),
              ),
              Positioned(
                left: 192.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedWidget135(),
              ),
              Positioned(
                left: 240.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedWidget136(),
              ),
              Positioned(
                left: 288.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedWidget137(),
              ),
              Positioned(
                left: 336.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedWidget138(),
              ),
              Positioned(
                left: 384.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedWidget139(),
              ),
              Positioned(
                left: 432.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedWidget140(),
              ),
              Positioned(
                left: 186.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedWidget141(),
              )
            ]),
      ),
    ));
  }
}
