import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedcategorywidget/generated/GeneratedCategoriesscrollableWidget.dart';
import 'package:flutterapp/money_managerapp/generatedcategorywidget/generated/GeneratedBigHeader1Widget1.dart';

/* Frame Category
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCategoryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 360.0,
                child: GeneratedCategoriesscrollableWidget(),
              ),
              Positioned(
                left: -6.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 123.0,
                child: GeneratedBigHeader1Widget1(),
              )
            ]),
      ),
    ));
  }
}
