import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/money_managerapp/generatedfrequencypopupwidget/generated/GeneratedMithngmtlnWidget.dart';
import 'package:flutterapp/money_managerapp/generatedfrequencypopupwidget/generated/GeneratedMitunmtlnWidget.dart';
import 'package:flutterapp/money_managerapp/generatedfrequencypopupwidget/generated/GeneratedMtlnWidget.dart';
import 'package:flutterapp/money_managerapp/generatedfrequencypopupwidget/generated/GeneratedHngngyWidget.dart';

/* Frame Frequency-popup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrequencypopupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 162.0,
        height: 108.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 10.0,
                top: null,
                right: null,
                bottom: null,
                width: 125.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 0.00, y: -33.50, z: 0, child: GeneratedMtlnWidget()),
              ),
              Positioned(
                left: 10.0,
                top: null,
                right: null,
                bottom: null,
                width: 128.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 0.00, y: -10.50, z: 0, child: GeneratedHngngyWidget()),
              ),
              Positioned(
                left: 10.0,
                top: null,
                right: null,
                bottom: null,
                width: 138.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 12.50, z: 0, child: GeneratedMitunmtlnWidget()),
              ),
              Positioned(
                left: 10.0,
                top: null,
                right: null,
                bottom: null,
                width: 144.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 35.50,
                    z: 0,
                    child: GeneratedMithngmtlnWidget()),
              )
            ]),
      ),
    ));
  }
}
