import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget/generated/GeneratedInputSearchWidget.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget/generated/GeneratedHeaderWidget13.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget/generated/GeneratedInputTypedTextWidget.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget/generated/GeneratedInputTextdownWidget3.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget/generated/GeneratedRadioSelectedWidget.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget/generated/GeneratedInputTextWidget21.dart';
import 'package:flutterapp/money_managerapp/generatedinputswidget/generated/GeneratedRadioUnselectedWidget.dart';

/* Frame Inputs
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1012.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 445.0,
                      height: 1012.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 236, 236, 236),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 450.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 73.0,
                              child: GeneratedInputSearchWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 544.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 73.0,
                              child: GeneratedRadioUnselectedWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 633.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 73.0,
                              child: GeneratedRadioSelectedWidget(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 8.0,
                              right: 8.0,
                              bottom: null,
                              width: null,
                              height: 128.0,
                              child: GeneratedHeaderWidget13(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 175.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 68.0,
                              child: GeneratedInputTypedTextWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 361.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 68.0,
                              child: GeneratedInputTextdownWidget3(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 68.0,
                              child: GeneratedInputTextWidget21(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
