import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedcurrencywidget/generated/GeneratedSmallHeaderWidget6.dart';
import 'package:flutterapp/money_managerapp/generatedcurrencywidget/generated/GeneratedContentContentBlockNoTitleWidget3.dart';
import 'package:flutterapp/money_managerapp/generatedcurrencywidget/generated/GeneratedVScrollDataWidget.dart';

/* Frame Currency
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCurrencyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 846.0,
                child: GeneratedVScrollDataWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 34.0,
                child: GeneratedContentContentBlockNoTitleWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedSmallHeaderWidget6(),
              )
            ]),
      ),
    ));
  }
}
