import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedHeaderWidget19.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedCategoryBlockWidget18.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedHeaderUserWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedDataBarChartBackgroundWidget16.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedTextimage_downWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedDataMobileGraphWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedDataBarChartFillWidget16.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedContentSearchResultWidget3.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedVScrollCategoryWidget2.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedContentItemWidget18.dart';
import 'package:flutterapp/money_managerapp/generateddatawidget18/generated/GeneratedVScrollDataWidget2.dart';

/* Frame Data
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDataWidget18 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1012.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1750.0,
                      height: 1012.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 236, 236, 236),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 141.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 278.0,
                              child: GeneratedDataMobileGraphWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 438.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 55.0,
                              child: GeneratedDataBarChartFillWidget16(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 438.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 15.0,
                              child: GeneratedDataBarChartBackgroundWidget16(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 8.0,
                              right: 8.0,
                              bottom: null,
                              width: null,
                              height: 128.0,
                              child: GeneratedHeaderWidget19(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 441.0,
                              right: null,
                              bottom: null,
                              width: 281.0,
                              height: 33.0,
                              child: GeneratedCategoryBlockWidget18(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 58.0,
                              child: GeneratedContentSearchResultWidget3(),
                            ),
                            Positioned(
                              left: 421.0,
                              top: 292.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 18.0,
                              child: GeneratedContentItemWidget18(),
                            ),
                            Positioned(
                              left: 870.0,
                              top: 141.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 846.0,
                              child: GeneratedVScrollDataWidget2(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 378.0,
                              right: null,
                              bottom: null,
                              width: 297.0,
                              height: 55.0,
                              child: GeneratedHeaderUserWidget1(),
                            ),
                            Positioned(
                              left: 1310.0,
                              top: 151.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 846.0,
                              child: GeneratedVScrollCategoryWidget2(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 254.0,
                              height: 204.0,
                              child: GeneratedTextimage_downWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
