import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedContentContentBlockSmallWidget.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedHeaderWidget18.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedMessageSendWidget.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedContentContentBlockLargeWidget.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedContentShareWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedContentMarketBlockWidget.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedContentSearchResultWidget.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedMessageReceiveWidget.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedContentContentBlockSmallWidget3.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedContentContentBlockNoTitleWidget5.dart';
import 'package:flutterapp/money_managerapp/generatedcontentwidget2/generated/GeneratedContentHeaderWidget4.dart';

/* Frame Content
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedContentWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1012.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1329.0,
                      height: 1012.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 236, 236, 236),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 100.0000228881836,
                              child: GeneratedContentContentBlockSmallWidget(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 100.0000228881836,
                              child: GeneratedContentContentBlockSmallWidget3(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 449.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 56.0,
                              child: GeneratedContentSearchResultWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 284.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 356.0,
                              child: GeneratedContentContentBlockLargeWidget(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 8.0,
                              right: 8.0,
                              bottom: null,
                              width: null,
                              height: 128.0,
                              child: GeneratedHeaderWidget18(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 673.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 215.0,
                              child: GeneratedContentMarketBlockWidget(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 149.0,
                              child: GeneratedMessageReceiveWidget(),
                            ),
                            Positioned(
                              left: 682.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 109.0,
                              child: GeneratedMessageSendWidget(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 521.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 34.0,
                              child:
                                  GeneratedContentContentBlockNoTitleWidget5(),
                            ),
                            Positioned(
                              left: 411.0,
                              top: 653.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 313.0,
                              child: GeneratedContentShareWidget1(),
                            ),
                            Positioned(
                              left: 825.0,
                              top: 329.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 15.0,
                              child: GeneratedContentHeaderWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
