import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedhomescreenwidget/generated/GeneratedCategoriesScrollableWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/money_managerapp/generatedhomescreenwidget/generated/GeneratedFrame247Widget1.dart';
import 'package:flutterapp/money_managerapp/generatedhomescreenwidget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/money_managerapp/generatedhomescreenwidget/generated/GeneratedProBigHeaderWidget.dart';

/* Frame Homescreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomescreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 2.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 178.0,
                      child: GeneratedProBigHeaderWidget(),
                    ),
                    Positioned(
                      left: 26.0,
                      top: 307.0,
                      right: null,
                      bottom: null,
                      width: 323.0,
                      height: 557.0,
                      child: GeneratedCategoriesScrollableWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 203.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 103.98054504394531,
              child: GeneratedFrame247Widget1(),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: 50.0,
              width: 64.0,
              height: 44.0,
              child: TransformHelper.translate(
                  x: 123.50, y: 0.00, z: 0, child: GeneratedGroupWidget()),
            )
          ]),
    ));
  }
}
