import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedloginwidget/generated/GeneratedQunmtkhuWidget.dart';
import 'package:flutterapp/money_managerapp/generatedloginwidget/generated/GeneratedInputTextWidget3.dart';
import 'package:flutterapp/money_managerapp/generatedloginwidget/generated/GeneratedButtonPrimaryWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedloginwidget/generated/GeneratedPageHeaderWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/money_managerapp/generatedloginwidget/generated/GeneratedInputTextWidget4.dart';
import 'package:flutterapp/money_managerapp/generatedloginwidget/generated/GeneratedIOSStatusBarBlackWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedloginwidget/generated/Generated3rdSignInWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedloginwidget/generated/GeneratedngnhpviWidget1.dart';

/* Frame Log In
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogInWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 128.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 194.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 350.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 313.0,
                width: 128.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 1.50, y: 0.00, z: 0, child: GeneratedQunmtkhuWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 191.0,
                width: 112.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 0.50, y: 0.00, z: 0, child: GeneratedngnhpviWidget1()),
              ),
              Positioned(
                left: 93.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 100.0,
                child: Generated3rdSignInWidget1(),
              )
            ]),
      ),
    ));
  }
}
