import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedcontactwidget/generated/GeneratedInputTextWidget19.dart';
import 'package:flutterapp/money_managerapp/generatedcontactwidget/generated/GeneratedInputTextWidget20.dart';
import 'package:flutterapp/money_managerapp/generatedcontactwidget/generated/GeneratedButtonPrimaryWidget9.dart';
import 'package:flutterapp/money_managerapp/generatedcontactwidget/generated/GeneratedInputTextdownWidget.dart';
import 'package:flutterapp/money_managerapp/generatedcontactwidget/generated/GeneratedSmallHeaderWidget4.dart';

/* Frame Contact
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedContactWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 307.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget9(),
              ),
              Positioned(
                left: 16.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 68.0,
                child: GeneratedInputTextdownWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedSmallHeaderWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 50.0,
                child: GeneratedInputTextWidget19(),
              ),
              Positioned(
                left: 16.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 50.0,
                child: GeneratedInputTextWidget20(),
              )
            ]),
      ),
    ));
  }
}
