import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedSmallTaskbarModeWidget4.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedTaskbarModeWidget22.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedPopupNotificationWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedBlackText1Widget2.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedRealTimeWidget3.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedImage37Widget.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedBigHeader1Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedBigTaskbarWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedSmallHeaderWidget7.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedBlurTextWidget6.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedIconWidget12.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedBigHeader2Widget1.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedBlackText2Widget12.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedText2Widget34.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedProBigHeaderWidget1.dart';
import 'package:flutterapp/money_managerapp/generateddata2widget/generated/GeneratedFrame247Widget2.dart';

/* Frame Data 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedData2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 923.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1181.0,
                      height: 923.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 236, 236, 236),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(45, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 383.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 123.0,
                              child: GeneratedBigHeader1Widget3(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 24.0,
                              child: GeneratedBlurTextWidget6(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 217.0,
                              right: null,
                              bottom: null,
                              width: 165.0,
                              height: 23.0,
                              child: GeneratedBlackText1Widget2(),
                            ),
                            Positioned(
                              left: 267.0,
                              top: 290.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 72.0,
                              child: GeneratedIconWidget12(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 145.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 25.0,
                              child: GeneratedBlackText2Widget12(),
                            ),
                            Positioned(
                              left: 569.0,
                              top: 494.0,
                              right: null,
                              bottom: null,
                              width: 47.0,
                              height: 38.0,
                              child: GeneratedText2Widget34(),
                            ),
                            Positioned(
                              left: 569.0,
                              top: 562.0,
                              right: null,
                              bottom: null,
                              width: 338.0,
                              height: 48.0,
                              child: GeneratedRealTimeWidget3(),
                            ),
                            Positioned(
                              left: 569.0,
                              top: 638.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 72.0,
                              child: GeneratedSmallHeaderWidget7(),
                            ),
                            Positioned(
                              left: 556.0,
                              top: 307.0,
                              right: null,
                              bottom: null,
                              width: 244.0,
                              height: 138.0,
                              child: GeneratedPopupNotificationWidget1(),
                            ),
                            Positioned(
                              left: 556.0,
                              top: 161.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 29.0,
                              child: GeneratedTaskbarModeWidget22(),
                            ),
                            Positioned(
                              left: 556.0,
                              top: 234.0,
                              right: null,
                              bottom: null,
                              width: 201.0,
                              height: 29.0,
                              child: GeneratedSmallTaskbarModeWidget4(),
                            ),
                            Positioned(
                              left: 562.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 29.0,
                              child: GeneratedBigTaskbarWidget1(),
                            ),
                            Positioned(
                              left: 68.0,
                              top: 560.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 123.0,
                              child: GeneratedBigHeader2Widget1(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 718.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 178.0,
                              child: GeneratedProBigHeaderWidget1(),
                            ),
                            Positioned(
                              left: 800.0,
                              top: 336.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 108.66669464111328,
                              child: GeneratedFrame247Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.021168501270110076;

                                final double height = constraints.maxHeight *
                                    0.027085590465872156;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2447078746824725,
                                      y: constraints.maxHeight *
                                          0.09534127843986999,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedImage37Widget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
