import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedaccountwidget/generated/GeneratedButtonPrimaryWidget6.dart';
import 'package:flutterapp/money_managerapp/generatedaccountwidget/generated/GeneratedSmallHeaderWidget2.dart';
import 'package:flutterapp/money_managerapp/generatedaccountwidget/generated/GeneratedGroup243Widget.dart';

/* Frame Account
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAccountWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedSmallHeaderWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 230.0,
                child: GeneratedGroup243Widget(),
              ),
              Positioned(
                left: 133.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget6(),
              )
            ]),
      ),
    ));
  }
}
