import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatednotificationwidget/generated/GeneratedContentContentBlockNoTitleWidget1.dart';
import 'package:flutterapp/money_managerapp/generatednotificationwidget/generated/GeneratedContentContentBlockNoTitleWidget2.dart';
import 'package:flutterapp/money_managerapp/generatednotificationwidget/generated/GeneratedSmallHeaderWidget5.dart';
import 'package:flutterapp/money_managerapp/generatednotificationwidget/generated/GeneratedButtonCreateWidget.dart';

/* Frame Notification
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotificationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 39.0,
                child: GeneratedButtonCreateWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 34.0,
                child: GeneratedContentContentBlockNoTitleWidget1(),
              ),
              Positioned(
                left: 17.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 34.0,
                child: GeneratedContentContentBlockNoTitleWidget2(),
              ),
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedSmallHeaderWidget5(),
              )
            ]),
      ),
    ));
  }
}
