import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedcreatereminderwidget/generated/GeneratedButtonPrimaryWidget2.dart';
import 'package:flutterapp/money_managerapp/generatedcreatereminderwidget/generated/GeneratedSmallHeaderWidget.dart';
import 'package:flutterapp/money_managerapp/generatedcreatereminderwidget/generated/GeneratedInputTextWidget5.dart';

/* Frame Create reminder 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCreatereminderWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 402.0,
                child: GeneratedInputTextWidget5(),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedSmallHeaderWidget(),
              ),
              Positioned(
                left: 140.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget2(),
              )
            ]),
      ),
    ));
  }
}
