import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedshareappwidget/generated/GeneratedContentShareWidget.dart';

/* Frame Share App
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedShareAppWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 374.0,
      height: 313.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 313.0,
              child: GeneratedContentShareWidget(),
            )
          ]),
    ));
  }
}
