import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX41Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX42Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX34Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX40Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX48Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX35Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX39Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX45Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX31Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX30Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX26Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX28Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX25Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX38Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX44Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX46Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX37Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX36Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX32Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX29Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX33Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX27Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX47Widget.dart';
import 'package:flutterapp/money_managerapp/generatedhidewidget/generated/GeneratedIPhoneX43Widget.dart';

/* Group Hide
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHideWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 3458.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 2450.0,
                    height: 3458.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX25Widget(),
                          ),
                          Positioned(
                            left: 415.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX26Widget(),
                          ),
                          Positioned(
                            left: 830.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX27Widget(),
                          ),
                          Positioned(
                            left: 1245.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX28Widget(),
                          ),
                          Positioned(
                            left: 1660.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX29Widget(),
                          ),
                          Positioned(
                            left: 2075.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX30Widget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 882.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX31Widget(),
                          ),
                          Positioned(
                            left: 415.0,
                            top: 882.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX32Widget(),
                          ),
                          Positioned(
                            left: 830.0,
                            top: 882.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX33Widget(),
                          ),
                          Positioned(
                            left: 2075.0,
                            top: 882.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX36Widget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 1764.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX37Widget(),
                          ),
                          Positioned(
                            left: 415.0,
                            top: 1764.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX38Widget(),
                          ),
                          Positioned(
                            left: 830.0,
                            top: 1764.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX39Widget(),
                          ),
                          Positioned(
                            left: 1245.0,
                            top: 1764.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX40Widget(),
                          ),
                          Positioned(
                            left: 1660.0,
                            top: 1764.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX41Widget(),
                          ),
                          Positioned(
                            left: 2075.0,
                            top: 1764.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX42Widget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 2646.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX43Widget(),
                          ),
                          Positioned(
                            left: 415.0,
                            top: 2646.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX44Widget(),
                          ),
                          Positioned(
                            left: 830.0,
                            top: 2646.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX45Widget(),
                          ),
                          Positioned(
                            left: 1245.0,
                            top: 2646.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX46Widget(),
                          ),
                          Positioned(
                            left: 1660.0,
                            top: 2646.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX47Widget(),
                          ),
                          Positioned(
                            left: 2075.0,
                            top: 2646.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX48Widget(),
                          ),
                          Positioned(
                            left: 1660.0,
                            top: 882.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX35Widget(),
                          ),
                          Positioned(
                            left: 1245.0,
                            top: 882.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 812.0,
                            child: GeneratedIPhoneX34Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
