import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedselectedwidget/generated/GeneratedButtonSelectedWidget1.dart';

/* Frame Selected
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelectedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 16.0,
      height: 16.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 16.0,
              height: 16.0,
              child: GeneratedButtonSelectedWidget1(),
            )
          ]),
    ));
  }
}
