import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedexchangemoneywidget/generated/GeneratedBigHeader1Widget2.dart';
import 'package:flutterapp/money_managerapp/generatedexchangemoneywidget/generated/GeneratedVScrollWidget1.dart';
import 'package:flutterapp/money_managerapp/generatedexchangemoneywidget/generated/GeneratedButtonPrimaryWidget8.dart';
import 'package:flutterapp/money_managerapp/generatedexchangemoneywidget/generated/GeneratedFrame247Widget.dart';

/* Frame Exchange money
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExchangemoneyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 554.0,
                child: GeneratedVScrollWidget1(),
              ),
              Positioned(
                left: 133.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget8(),
              ),
              Positioned(
                left: -6.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 123.0,
                child: GeneratedBigHeader1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 108.66669464111328,
                child: GeneratedFrame247Widget(),
              )
            ]),
      ),
    ));
  }
}
