import 'package:flutter/material.dart';
import 'package:flutterapp/money_managerapp/generatedleftnavigationpanewidget/generated/GeneratedVScrollCategoryWidget.dart';

/* Frame Left Navigation Pane
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLeftNavigationPaneWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 297.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 812.0,
                child: GeneratedVScrollCategoryWidget(),
              )
            ]),
      ),
    ));
  }
}
